name: tagfinder_env

channels:
  - conda-forge

dependencies:
  # R
  - r-base=4.3

  # Build tools
  - git
  - make
  - cmake>=3.20,<4

  # CUDA host compiler (required for Ripser++)
  - gcc_linux-64=8
  - gxx_linux-64=8
