#!/usr/bin/env Rscript

################################################################################
# Module 3: Feature composition extraction from persistent homology features
#
# Purpose:
#   Link each persistent homology interval from Module 2 back to the biological
#   features in the Module 1 filtration matrix. For each target topological
#   feature, this module estimates birth composition, death composition, and
#   total feature composition. The output is the direct input for Module 4
#   participation score calculation.
#
# Expected inputs:
#   1) Module 1 output manifest:
#      <prefix>_module1_output_manifest.tsv
#      Required columns: phenotype, safe_phenotype_label, topPct_matrix,
#                        topPct_numeric_matrix
#
#   2) Module 2 input manifest:
#      <prefix>_module3_input_manifest.tsv
#      Required columns: matrix_id, matrix_path, barcode_table
#
#   3) Module 2 barcode tables generated by module2_persistent_homology.R
#
# Main outputs:
#   1) Per-phenotype/matrix composition tables
#   2) Combined composition table
#   3) Composition extraction summary
#   4) Module 4 input manifest
#
# Design principles:
#   - no hard-coded paths
#   - compatible with generic phenotype labels, not cancer-specific labels
#   - standardized input/output schemas across modules
#   - explicit validation and informative error messages
#   - modular functions to avoid copy-and-paste
################################################################################

options(stringsAsFactors = FALSE)

##### 1. Lightweight command-line parser ######################################

parse_args <- function(argv) {
  args <- list()
  i <- 1
  while (i <= length(argv)) {
    key <- argv[[i]]
    if (!startsWith(key, "--")) {
      stop("Unexpected argument: ", key, "\nArguments must use --key value format.", call. = FALSE)
    }
    key <- sub("^--", "", key)
    if (i == length(argv) || startsWith(argv[[i + 1]], "--")) {
      args[[key]] <- TRUE
      i <- i + 1
    } else {
      args[[key]] <- argv[[i + 1]]
      i <- i + 2
    }
  }
  args
}

get_arg <- function(args, name, default = NULL, required = FALSE) {
  value <- args[[name]]
  if (is.null(value)) {
    if (required) stop("Missing required argument: --", name, call. = FALSE)
    return(default)
  }
  value
}

as_logical_arg <- function(x) {
  if (is.logical(x)) return(x)
  x <- tolower(as.character(x))
  if (x %in% c("true", "t", "1", "yes", "y")) return(TRUE)
  if (x %in% c("false", "f", "0", "no", "n")) return(FALSE)
  stop("Cannot parse logical value: ", x, call. = FALSE)
}

print_usage <- function() {
  cat(
"\nModule 3: Feature composition extraction\n\n",
"Required arguments:\n",
"  --module1-manifest <tsv>   Module 1 output manifest.\n",
"  --module2-manifest <tsv>   Module 2 manifest for Module 3 input.\n",
"  --outdir <directory>       Output directory.\n\n",
"Common optional arguments:\n",
"  --prefix <string>          Output prefix. Default: analysis\n",
"  --target-dim <integer>     Homology dimension to analyze. Default: 1\n",
"  --mode <birth_death|birth_only>  Composition mode. Default: birth_death\n",
"  --birth-choice <largest|first|smallest>  How to select among multiple birth candidates. Default: largest\n",
"  --value-digits <integer>   Digits used for value matching keys. Default: 10\n",
"  --max-boundary-pairs <integer>  Safety cap for boundary-pair candidates per value. Default: 20000\n",
"  --keep-failed <true|false> Keep failed features in output. Default: true\n",
"  --verbose <true|false>     Print progress messages. Default: true\n\n",
"Example:\n",
"  Rscript module3_feature_composition.R \\\n",
"    --module1-manifest module1_output/demo_module1_output_manifest.tsv \\\n",
"    --module2-manifest module2_output/demo_module3_input_manifest.tsv \\\n",
"    --outdir module3_output \\\n",
"    --prefix demo \\\n",
"    --target-dim 1\n\n",
sep = "")
}

##### 2. General utilities #####################################################

message_info <- function(...) message("[INFO] ", paste0(..., collapse = ""))
message_warn <- function(...) warning(paste0(..., collapse = ""), call. = FALSE)
stop_error <- function(...) stop(paste0(..., collapse = ""), call. = FALSE)

ensure_dir <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE, showWarnings = FALSE)
  if (!dir.exists(path)) stop_error("Failed to create output directory: ", path)
}

check_file_exists <- function(path, label) {
  if (is.null(path) || is.na(path) || !file.exists(path)) {
    stop_error(label, " not found: ", path)
  }
}

normalize_path_if_exists <- function(path) {
  if (is.na(path) || is.null(path)) return(NA_character_)
  if (file.exists(path)) return(normalizePath(path, mustWork = TRUE))
  path
}

write_tsv <- function(df, path) {
  write.table(df, file = path, sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)
}

read_table_auto <- function(path) {
  check_file_exists(path, "Table")
  ext <- tolower(tools::file_ext(path))
  sep <- if (ext == "csv") "," else "\t"
  utils::read.table(
    path,
    sep = sep,
    header = TRUE,
    quote = "\"",
    comment.char = "",
    check.names = FALSE,
    stringsAsFactors = FALSE
  )
}

sanitize_label <- function(x) {
  x <- gsub("[^A-Za-z0-9_.-]+", "_", as.character(x))
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  ifelse(nchar(x) == 0, "label", x)
}

value_key <- function(x, digits = 10) {
  ifelse(is.finite(x), sprintf(paste0("%.", digits, "g"), x), as.character(x))
}

collapse_ids <- function(x) {
  x <- unique(as.character(x[!is.na(x) & x != ""]))
  if (length(x) == 0) return(NA_character_)
  paste(sort(x), collapse = ";")
}

##### 3. Input validation and matching ########################################

validate_columns <- function(df, cols, label) {
  missing <- setdiff(cols, colnames(df))
  if (length(missing) > 0) {
    stop_error(label, " is missing required column(s): ", paste(missing, collapse = ", "))
  }
}

load_named_matrix <- function(path) {
  check_file_exists(path, "Named filtration matrix")
  df <- read_table_auto(path)
  if (ncol(df) < 3) stop_error("Named matrix must include row IDs plus at least two feature columns: ", path)

  row_ids <- df[[1]]
  mat_df <- df[, -1, drop = FALSE]
  mat <- as.matrix(mat_df)
  suppressWarnings(storage.mode(mat) <- "numeric")

  if (any(is.na(mat) & !is.na(as.matrix(mat_df)))) {
    stop_error("Named matrix contains non-numeric values: ", path)
  }
  if (nrow(mat) != ncol(mat)) {
    stop_error("Named matrix must be square after removing the first row-ID column: ", path)
  }
  if (length(row_ids) != ncol(mat)) {
    stop_error("Number of row IDs does not match number of matrix columns: ", path)
  }

  rownames(mat) <- as.character(row_ids)
  colnames(mat) <- colnames(mat_df)

  if (!identical(rownames(mat), colnames(mat))) {
    stop_error(
      "Row and column feature names are not identical or not in the same order: ", path,
      "\nModule 3 requires a symmetric feature-feature matrix with matching dimnames."
    )
  }
  if (any(!is.finite(mat[upper.tri(mat)]))) {
    stop_error("Named matrix contains non-finite off-diagonal values: ", path)
  }
  mat
}

match_module_manifests <- function(module1_manifest, module2_manifest) {
  validate_columns(
    module1_manifest,
    c("phenotype", "safe_phenotype_label", "topPct_matrix", "topPct_numeric_matrix"),
    "Module 1 manifest"
  )
  validate_columns(
    module2_manifest,
    c("matrix_id", "matrix_path", "barcode_table"),
    "Module 2 manifest"
  )

  m1 <- module1_manifest
  m2 <- module2_manifest
  m1$topPct_numeric_matrix_norm <- vapply(m1$topPct_numeric_matrix, normalize_path_if_exists, character(1))
  m1$topPct_matrix_norm <- vapply(m1$topPct_matrix, normalize_path_if_exists, character(1))
  m2$matrix_path_norm <- vapply(m2$matrix_path, normalize_path_if_exists, character(1))
  m2$barcode_table_norm <- vapply(m2$barcode_table, normalize_path_if_exists, character(1))

  merged <- merge(
    m2,
    m1,
    by.x = "matrix_path_norm",
    by.y = "topPct_numeric_matrix_norm",
    all.x = TRUE,
    sort = FALSE
  )

  if (any(is.na(merged$topPct_matrix))) {
    unmatched <- merged$matrix_path[is.na(merged$topPct_matrix)]
    stop_error(
      "Failed to match Module 2 matrix_path to Module 1 topPct_numeric_matrix for: ",
      paste(unmatched, collapse = ", "),
      "\nPlease provide matching Module 1 and Module 2 manifests."
    )
  }

  merged
}

load_barcode_table <- function(path, target_dim) {
  check_file_exists(path, "Barcode table")
  df <- read_table_auto(path)
  validate_columns(
    df,
    c("matrix_id", "homology_feature_id", "dimension", "birth", "death", "lifespan", "is_infinite"),
    "Barcode table"
  )
  df$dimension <- as.integer(df$dimension)
  df$birth <- as.numeric(df$birth)
  df$death <- as.numeric(df$death)
  df$lifespan <- as.numeric(df$lifespan)
  df <- df[df$dimension == target_dim, , drop = FALSE]
  df <- df[is.finite(df$birth), , drop = FALSE]
  df
}

##### 4. Edge lookup and composition logic ####################################

build_edge_lookup_for_values <- function(mat, needed_values, value_digits = 10, max_boundary_pairs = 20000) {
  needed_values <- needed_values[is.finite(needed_values)]
  if (length(needed_values) == 0) return(list())

  needed_keys <- unique(value_key(needed_values, digits = value_digits))
  upper_idx <- which(upper.tri(mat), arr.ind = TRUE)
  vals <- mat[upper_idx]
  keys <- value_key(vals, digits = value_digits)
  hit <- keys %in% needed_keys

  if (!any(hit)) return(list())

  hit_df <- data.frame(
    i = upper_idx[hit, 1],
    j = upper_idx[hit, 2],
    key = keys[hit],
    stringsAsFactors = FALSE
  )
  split_df <- split(hit_df, hit_df$key)
  lapply(split_df, function(d) {
    if (nrow(d) > max_boundary_pairs) {
      d <- d[seq_len(max_boundary_pairs), , drop = FALSE]
    }
    as.matrix(d[, c("i", "j"), drop = FALSE])
  })
}

compute_birth_composition_for_pair <- function(mat, boundary_pair, birth) {
  a <- boundary_pair[[1]]
  b <- boundary_pair[[2]]

  overlap_check <- as.integer(mat[a, ] < birth) + as.integer(mat[b, ] < birth)
  if (max(overlap_check) == 2) return(NULL)
  if (sum(overlap_check) == 2) return(NULL)

  set1 <- which(mat[a, ] < birth)
  set2 <- which(mat[b, ] < birth)
  boundary_set <- sort(c(set1, set2))

  for (i in set1) {
    subset <- which(mat[i, ] < birth)
    sub_boundary <- sort(table(c(subset, set2)), decreasing = TRUE)
    sub_boundary <- sub_boundary[sub_boundary > 1]
    if (length(sub_boundary) > 0) {
      boundary_set <- c(boundary_set, as.integer(names(sub_boundary)), i)
    }
  }

  boundary_set <- c(boundary_set, a, b)
  freq_set <- sort(table(boundary_set), decreasing = TRUE)

  guard <- 0
  while (length(freq_set) > 0 && max(freq_set) == 1) {
    guard <- guard + 1
    if (guard > nrow(mat)) break

    tested_set <- c(set1, set2)
    untested_set <- setdiff(boundary_set, tested_set)
    if (length(untested_set) == 0) break

    for (i in untested_set) {
      subset <- which(mat[i, ] < birth)
      sub_boundary <- sort(table(c(subset, set2)), decreasing = TRUE)
      sub_boundary <- sub_boundary[sub_boundary > 1]
      if (length(sub_boundary) > 0) {
        boundary_set <- c(boundary_set, as.integer(names(sub_boundary)))
      }
    }

    boundary_set <- c(boundary_set, untested_set)
    freq_set <- sort(table(boundary_set), decreasing = TRUE)
  }

  sort(unique(as.integer(boundary_set)))
}

compute_death_composition_for_pair <- function(mat, boundary_pair, death) {
  if (!is.finite(death)) return(NULL)
  a <- boundary_pair[[1]]
  b <- boundary_pair[[2]]

  overlap_check <- as.integer(mat[a, ] < death) + as.integer(mat[b, ] < death)
  if (max(overlap_check) != 2) return(NULL)

  set1 <- which(mat[a, ] <= death)
  set2 <- which(mat[b, ] <= death)
  boundary_set <- sort(c(set1, set2))
  freq_set <- sort(table(boundary_set), decreasing = TRUE)
  res <- as.integer(names(freq_set[freq_set > 1]))
  sort(res)
}

pick_candidate <- function(candidate_list, strategy = "largest") {
  candidate_list <- candidate_list[!vapply(candidate_list, is.null, logical(1))]
  if (length(candidate_list) == 0) return(NULL)
  if (length(candidate_list) == 1) return(candidate_list[[1]])

  sizes <- vapply(candidate_list, length, integer(1))
  if (strategy == "first") return(candidate_list[[1]])
  if (strategy == "smallest") return(candidate_list[[which.min(sizes)]])
  candidate_list[[which.max(sizes)]]
}

idx_to_feature_ids <- function(idx, feature_ids) {
  idx <- idx[!is.na(idx) & idx >= 1 & idx <= length(feature_ids)]
  if (length(idx) == 0) return(character())
  feature_ids[sort(unique(idx))]
}

extract_composition_one_barcode <- function(barcode_df, mat, matrix_id, phenotype,
                                            mode = "birth_death",
                                            birth_choice = "largest",
                                            value_digits = 10,
                                            max_boundary_pairs = 20000,
                                            verbose = TRUE) {
  feature_ids <- rownames(mat)

  finite_deaths <- barcode_df$death[is.finite(barcode_df$death)]
  needed_values <- barcode_df$birth
  if (mode == "birth_death") needed_values <- c(needed_values, finite_deaths)
  edge_lookup <- build_edge_lookup_for_values(
    mat = mat,
    needed_values = needed_values,
    value_digits = value_digits,
    max_boundary_pairs = max_boundary_pairs
  )

  records <- vector("list", nrow(barcode_df))
  for (i in seq_len(nrow(barcode_df))) {
    if (verbose && (i == 1 || i == nrow(barcode_df) || i %% 1000 == 0)) {
      message_info("  feature ", i, "/", nrow(barcode_df), " for ", matrix_id)
    }

    row <- barcode_df[i, , drop = FALSE]
    birth <- row$birth[[1]]
    death <- row$death[[1]]

    birth_key <- value_key(birth, digits = value_digits)
    birth_pairs <- edge_lookup[[birth_key]]
    birth_idx <- NULL
    death_idx <- NULL
    birth_pair_used <- c(NA_integer_, NA_integer_)
    death_pair_used <- c(NA_integer_, NA_integer_)
    status <- "ok"
    message <- ""

    if (is.null(birth_pairs) || nrow(birth_pairs) == 0) {
      status <- "failed"
      message <- "No birth boundary pair found for the barcode birth value."
    } else {
      birth_candidates <- lapply(seq_len(nrow(birth_pairs)), function(k) {
        compute_birth_composition_for_pair(mat, birth_pairs[k, ], birth)
      })
      birth_idx <- pick_candidate(birth_candidates, strategy = birth_choice)

      if (is.null(birth_idx)) {
        status <- "failed"
        message <- "Birth composition could not be determined from candidate boundary pairs."
      } else {
        candidate_sizes <- vapply(birth_candidates, function(x) if (is.null(x)) NA_integer_ else length(x), integer(1))
        valid_candidate <- which(!is.na(candidate_sizes))
        if (length(valid_candidate) > 0) {
          if (birth_choice == "first") use_k <- valid_candidate[[1]]
          else if (birth_choice == "smallest") use_k <- valid_candidate[[which.min(candidate_sizes[valid_candidate])]]
          else use_k <- valid_candidate[[which.max(candidate_sizes[valid_candidate])]]
          birth_pair_used <- birth_pairs[use_k, ]
        }
      }
    }

    if (status == "ok" && mode == "birth_death" && is.finite(death)) {
      death_key <- value_key(death, digits = value_digits)
      death_pairs <- edge_lookup[[death_key]]
      if (is.null(death_pairs) || nrow(death_pairs) == 0) {
        message <- "No death boundary pair found; birth composition retained."
      } else {
        death_candidates <- lapply(seq_len(nrow(death_pairs)), function(k) {
          compute_death_composition_for_pair(mat, death_pairs[k, ], death)
        })
        death_idx <- pick_candidate(death_candidates, strategy = "largest")
        if (!is.null(death_idx)) {
          candidate_sizes <- vapply(death_candidates, function(x) if (is.null(x)) NA_integer_ else length(x), integer(1))
          valid_candidate <- which(!is.na(candidate_sizes))
          use_k <- valid_candidate[[which.max(candidate_sizes[valid_candidate])]]
          death_pair_used <- death_pairs[use_k, ]
        } else {
          message <- "Death composition could not be determined; birth composition retained."
        }
      }
    }

    birth_features <- idx_to_feature_ids(birth_idx, feature_ids)
    death_features <- idx_to_feature_ids(death_idx, feature_ids)
    total_features <- unique(c(birth_features, death_features))

    records[[i]] <- data.frame(
      matrix_id = matrix_id,
      phenotype = phenotype,
      homology_feature_id = row$homology_feature_id[[1]],
      dimension = row$dimension[[1]],
      birth = birth,
      death = death,
      lifespan = row$lifespan[[1]],
      is_infinite = row$is_infinite[[1]],
      birth_edge_feature1 = ifelse(is.na(birth_pair_used[[1]]), NA_character_, feature_ids[[birth_pair_used[[1]]]]),
      birth_edge_feature2 = ifelse(is.na(birth_pair_used[[2]]), NA_character_, feature_ids[[birth_pair_used[[2]]]]),
      death_edge_feature1 = ifelse(is.na(death_pair_used[[1]]), NA_character_, feature_ids[[death_pair_used[[1]]]]),
      death_edge_feature2 = ifelse(is.na(death_pair_used[[2]]), NA_character_, feature_ids[[death_pair_used[[2]]]]),
      n_birth_composition = length(birth_features),
      n_death_composition = length(death_features),
      n_total_composition = length(total_features),
      birth_composition = collapse_ids(birth_features),
      death_composition = collapse_ids(death_features),
      total_composition = collapse_ids(total_features),
      status = status,
      message = message,
      stringsAsFactors = FALSE
    )
  }

  do.call(rbind, records)
}

summarize_composition <- function(df) {
  if (nrow(df) == 0) {
    return(data.frame(
      matrix_id = character(), phenotype = character(), dimension = integer(),
      n_intervals = integer(), n_ok = integer(), n_failed = integer(),
      median_birth_comp_size = numeric(), median_total_comp_size = numeric(),
      stringsAsFactors = FALSE
    ))
  }

  keys <- paste(df$matrix_id, df$phenotype, df$dimension, sep = "\t")
  out <- lapply(split(df, keys), function(x) {
    ok <- x[x$status == "ok", , drop = FALSE]
    data.frame(
      matrix_id = x$matrix_id[[1]],
      phenotype = x$phenotype[[1]],
      dimension = x$dimension[[1]],
      n_intervals = nrow(x),
      n_ok = sum(x$status == "ok"),
      n_failed = sum(x$status != "ok"),
      median_birth_comp_size = ifelse(nrow(ok) > 0, stats::median(ok$n_birth_composition, na.rm = TRUE), NA_real_),
      median_total_comp_size = ifelse(nrow(ok) > 0, stats::median(ok$n_total_composition, na.rm = TRUE), NA_real_),
      stringsAsFactors = FALSE
    )
  })
  do.call(rbind, out)
}

##### 5. Main workflow #########################################################

main <- function() {
  argv <- commandArgs(trailingOnly = TRUE)
  if (length(argv) == 0 || any(argv %in% c("--help", "-h"))) {
    print_usage()
    quit(save = "no", status = 0)
  }

  args <- parse_args(argv)

  module1_manifest_path <- get_arg(args, "module1-manifest", required = TRUE)
  module2_manifest_path <- get_arg(args, "module2-manifest", required = TRUE)
  outdir <- get_arg(args, "outdir", required = TRUE)
  prefix <- get_arg(args, "prefix", default = "analysis")
  target_dim <- as.integer(get_arg(args, "target-dim", default = "1"))
  mode <- get_arg(args, "mode", default = "birth_death")
  birth_choice <- get_arg(args, "birth-choice", default = "largest")
  value_digits <- as.integer(get_arg(args, "value-digits", default = "10"))
  max_boundary_pairs <- as.integer(get_arg(args, "max-boundary-pairs", default = "20000"))
  keep_failed <- as_logical_arg(get_arg(args, "keep-failed", default = "true"))
  verbose <- as_logical_arg(get_arg(args, "verbose", default = "true"))

  if (!mode %in% c("birth_death", "birth_only")) {
    stop_error("--mode must be birth_death or birth_only.")
  }
  if (!birth_choice %in% c("largest", "first", "smallest")) {
    stop_error("--birth-choice must be largest, first, or smallest.")
  }
  if (is.na(target_dim) || target_dim < 0) stop_error("--target-dim must be a non-negative integer.")
  if (is.na(value_digits) || value_digits < 1) stop_error("--value-digits must be a positive integer.")
  if (is.na(max_boundary_pairs) || max_boundary_pairs < 1) stop_error("--max-boundary-pairs must be a positive integer.")
  if (target_dim != 1) {
    message_warn(
      "This implementation is primarily designed for H1 feature composition. ",
      "Proceeding with target_dim=", target_dim, ", but biological interpretation should be checked carefully."
    )
  }

  ensure_dir(outdir)
  comp_dir <- file.path(outdir, "composition_tables")
  log_dir <- file.path(outdir, "logs")
  ensure_dir(comp_dir)
  ensure_dir(log_dir)

  message_info("Loading Module 1 manifest: ", module1_manifest_path)
  module1_manifest <- read_table_auto(module1_manifest_path)
  message_info("Loading Module 2 manifest: ", module2_manifest_path)
  module2_manifest <- read_table_auto(module2_manifest_path)

  matched_manifest <- match_module_manifests(module1_manifest, module2_manifest)
  if (nrow(matched_manifest) == 0) stop_error("No matched Module 1/Module 2 records found.")

  all_records <- list()
  module4_manifest_records <- vector("list", nrow(matched_manifest))

  for (i in seq_len(nrow(matched_manifest))) {
    rec <- matched_manifest[i, , drop = FALSE]
    matrix_id <- rec$matrix_id[[1]]
    phenotype <- rec$phenotype[[1]]
    safe_pheno <- rec$safe_phenotype_label[[1]]
    top_matrix_path <- rec$topPct_matrix[[1]]
    barcode_path <- rec$barcode_table[[1]]

    message_info("Processing [", i, "/", nrow(matched_manifest), "]: ", matrix_id, " | phenotype=", phenotype)

    top_mat <- load_named_matrix(top_matrix_path)
    barcode_df <- load_barcode_table(barcode_path, target_dim = target_dim)

    if (nrow(barcode_df) == 0) {
      message_warn("No H", target_dim, " barcode intervals found for matrix_id=", matrix_id)
      comp_df <- data.frame(
        matrix_id = character(), phenotype = character(), homology_feature_id = character(),
        dimension = integer(), birth = numeric(), death = numeric(), lifespan = numeric(),
        is_infinite = logical(), birth_edge_feature1 = character(), birth_edge_feature2 = character(),
        death_edge_feature1 = character(), death_edge_feature2 = character(),
        n_birth_composition = integer(), n_death_composition = integer(), n_total_composition = integer(),
        birth_composition = character(), death_composition = character(), total_composition = character(),
        status = character(), message = character(), stringsAsFactors = FALSE
      )
    } else {
      comp_df <- extract_composition_one_barcode(
        barcode_df = barcode_df,
        mat = top_mat,
        matrix_id = matrix_id,
        phenotype = phenotype,
        mode = mode,
        birth_choice = birth_choice,
        value_digits = value_digits,
        max_boundary_pairs = max_boundary_pairs,
        verbose = verbose
      )
      if (!keep_failed) comp_df <- comp_df[comp_df$status == "ok", , drop = FALSE]
    }

    comp_path <- file.path(comp_dir, paste0(prefix, "_", sanitize_label(matrix_id), "_H", target_dim, "_composition.tsv"))
    write_tsv(comp_df, comp_path)
    all_records[[matrix_id]] <- comp_df

    module4_manifest_records[[i]] <- data.frame(
      matrix_id = matrix_id,
      phenotype = phenotype,
      safe_phenotype_label = safe_pheno,
      target_dimension = target_dim,
      topPct_matrix = normalize_path_if_exists(top_matrix_path),
      barcode_table = normalize_path_if_exists(barcode_path),
      composition_table = normalize_path_if_exists(comp_path),
      stringsAsFactors = FALSE
    )
  }

  combined <- do.call(rbind, all_records)
  if (is.null(combined)) combined <- data.frame()

  combined_path <- file.path(outdir, paste0(prefix, "_module3_composition_all.tsv"))
  summary_path <- file.path(outdir, paste0(prefix, "_module3_composition_summary.tsv"))
  matched_manifest_path <- file.path(outdir, paste0(prefix, "_module3_matched_input_manifest.tsv"))
  module4_manifest_path <- file.path(outdir, paste0(prefix, "_module4_input_manifest.tsv"))
  run_info_path <- file.path(outdir, paste0(prefix, "_module3_run_info.tsv"))

  write_tsv(combined, combined_path)
  write_tsv(summarize_composition(combined), summary_path)
  write_tsv(matched_manifest, matched_manifest_path)
  module4_manifest <- do.call(rbind, module4_manifest_records)
  
  module4_manifest$composition_all_path <-
    normalize_path_if_exists(combined_path)
  write_tsv(module4_manifest, module4_manifest_path)

  run_info <- data.frame(
    parameter = c(
      "module1_manifest", "module2_manifest", "prefix", "target_dim", "mode",
      "birth_choice", "value_digits", "max_boundary_pairs", "keep_failed",
      "combined_composition", "module4_input_manifest"
    ),
    value = c(
      module1_manifest_path, module2_manifest_path, prefix, target_dim, mode,
      birth_choice, value_digits, max_boundary_pairs, keep_failed,
      combined_path, module4_manifest_path
    ),
    stringsAsFactors = FALSE
  )
  write_tsv(run_info, run_info_path)

  message_info("Module 3 completed.")
  message_info("Combined composition table: ", combined_path)
  message_info("Composition summary: ", summary_path)
  message_info("Module 4 input manifest: ", module4_manifest_path)
}

main()
