#!/usr/bin/env Rscript

################################################################################
# Module 2: Persistent homology analysis
#
# Purpose:
#   Run Ripser++ on phenotype-specific numeric filtration matrices generated by
#   Module 1 and parse Ripser++ text outputs into standardized barcode tables.
#
# Expected input from Module 1:
#   <prefix>_module2_ripser_input_list.txt
#   Each non-empty, non-comment line contains one numeric matrix path.
#   Numeric matrices should be square, tab-delimited, and contain no row/column names.
#
# Main outputs:
#   1) Raw Ripser++ output text files
#   2) Parsed barcode tables for each input matrix
#   3) A combined barcode table across all phenotype/network matrices
#   4) Per-network homology summary table
#   5) Module 3 input manifest
#   6) Run manifest recording commands, exit codes, and output paths
#   7) Overlaid H0 and H1 topological-index plots (PNG and/or PDF)
#   8) Plot manifest recording dimension-specific figure paths
#
# Design principles:
#   - no hard-coded paths
#   - single input list from Module 1
#   - consistent output naming and table schemas
#   - explicit validation and informative error messages
#   - parses PH output once so downstream modules do not repeat parser logic
################################################################################

options(stringsAsFactors = FALSE)

##### 1. Lightweight command-line parser ######################################

parse_args <- function(argv) {
  args <- list()
  i <- 1
  while (i <= length(argv)) {
    key <- argv[[i]]
    if (!startsWith(key, "--")) {
      stop("Unexpected argument: ", key, "\nArguments must use --key value format.", call. = FALSE)
    }
    key <- sub("^--", "", key)
    if (i == length(argv) || startsWith(argv[[i + 1]], "--")) {
      args[[key]] <- TRUE
      i <- i + 1
    } else {
      args[[key]] <- argv[[i + 1]]
      i <- i + 2
    }
  }
  args
}

get_arg <- function(args, name, default = NULL, required = FALSE) {
  value <- args[[name]]
  if (is.null(value)) {
    if (required) stop("Missing required argument: --", name, call. = FALSE)
    return(default)
  }
  value
}

as_logical_arg <- function(x) {
  if (is.logical(x)) return(x)
  x <- tolower(as.character(x))
  if (x %in% c("true", "t", "1", "yes", "y")) return(TRUE)
  if (x %in% c("false", "f", "0", "no", "n")) return(FALSE)
  stop("Cannot parse logical value: ", x, call. = FALSE)
}

print_usage <- function() {
  cat(
    "\nModule 2: Persistent homology analysis\n\n",
    "Required arguments:\n",
    "  --input-list <txt>       Module 1 output list containing numeric matrix paths.\n",
    "  --ripser-bin <path>      Path to ripser++ executable.\n",
    "  --outdir <directory>     Output directory.\n\n",
    "Common optional arguments:\n",
    "  --prefix <string>        Output prefix. Default: analysis\n",
    "  --format <string>        Ripser++ format. Default: distance\n",
    "  --max-dim <integer>      Maximum homology dimension. Default: 1\n",
    "  --threshold <numeric>    Ripser++ filtration threshold. Default: 100\n",
    "  --ratio <numeric>        Ripser++ ratio argument. Default: 1\n",
    "  --sparse <true|false>    Add --sparse to Ripser++ command. Default: true\n",
    "  --gpu-id <id>            Optional CUDA_VISIBLE_DEVICES value.\n",
    "  --extra-args <string>    Extra Ripser++ arguments, passed after standard options.\n",
    "  --validate-matrix <true|false>  Validate numeric matrix shape before running. Default: true\n",
    "  --run-ripser <true|false>       If false, only parse existing raw outputs. Default: true\n",
    "  --continue-on-error <true|false> Continue if one matrix fails. Default: true\n\n",
    "Plot arguments:\n",
    "  --make-plots <true|false> Generate overlaid H0/H1 plots. Default: true\n",
    "  --plot-format <png|pdf|both> Figure format. Default: both\n",
    "  --plot-labels <a,b>      Optional comma-separated group labels in input-list order.\n",
    "  --plot-colors <a,b>      Optional comma-separated colors. Default: #56B4E9,#E64B4B\n",
    "  --plot-width <numeric>   Figure width in inches. Default: 6\n",
    "  --plot-height <numeric>  Figure height in inches. Default: 6\n",
    "  --plot-dpi <integer>     PNG resolution. Default: 300\n\n",
    "Example:\n",
    "  Rscript module2_persistent_homology.R \\\n",
    "    --input-list module1_output/demo_module2_ripser_input_list.txt \\\n",
    "    --ripser-bin /path/to/ripser++ \\\n",
    "    --outdir module2_output \\\n",
    "    --prefix demo \\\n",
    "    --max-dim 1 \\\n",
    "    --threshold 100 \\\n",
    "    --gpu-id 0\n\n",
    sep = "")
}

##### 2. General utilities #####################################################

message_info <- function(...) message("[INFO] ", paste0(..., collapse = ""))
message_warn <- function(...) warning(paste0(..., collapse = ""), call. = FALSE)
stop_error <- function(...) stop(paste0(..., collapse = ""), call. = FALSE)

ensure_dir <- function(path) {
  if (!dir.exists(path)) dir.create(path, recursive = TRUE, showWarnings = FALSE)
  if (!dir.exists(path)) stop_error("Failed to create output directory: ", path)
}

check_file_exists <- function(path, label) {
  if (is.null(path) || !file.exists(path)) stop_error(label, " not found: ", path)
}

normalize_path_if_exists <- function(path) {
  if (file.exists(path)) return(normalizePath(path, mustWork = TRUE))
  path
}

sanitize_id <- function(x) {
  x <- basename(as.character(x))
  x <- sub("\\.tsv$", "", x, ignore.case = TRUE)
  x <- sub("\\.txt$", "", x, ignore.case = TRUE)
  x <- sub("_topPct_numeric$", "", x)
  x <- sub("_topPct\\.numeric$", "", x)
  x <- sub("_topPct$", "", x)
  x <- gsub("[^A-Za-z0-9_.-]+", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  ifelse(nchar(x) == 0, "matrix", x)
}

write_tsv <- function(df, path) {
  write.table(df, file = path, sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)
}

read_input_list <- function(path) {
  check_file_exists(path, "Input list")
  lines <- readLines(path, warn = FALSE)
  lines <- trimws(lines)
  lines <- lines[lines != "" & !startsWith(lines, "#")]
  if (length(lines) == 0) stop_error("Input list contains no usable matrix paths: ", path)
  
  data.frame(
    matrix_id = make.unique(vapply(lines, sanitize_id, character(1)), sep = "_"),
    matrix_path = vapply(lines, normalize_path_if_exists, character(1)),
    stringsAsFactors = FALSE
  )
}

##### 3. Numeric matrix validation ############################################

is_numeric_token <- function(x) {
  grepl("^[+-]?((([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([eE][+-]?[0-9]+)?|Inf|-Inf|NaN|NA)$", x)
}

validate_numeric_matrix_file <- function(path) {
  check_file_exists(path, "Numeric matrix")
  
  first_line <- readLines(path, n = 1, warn = FALSE)
  if (length(first_line) == 0 || trimws(first_line) == "") {
    stop_error("Numeric matrix is empty: ", path)
  }
  
  first_tokens <- strsplit(first_line, "\t", fixed = TRUE)[[1]]
  if (length(first_tokens) < 2) {
    stop_error("Numeric matrix must have at least two columns: ", path)
  }
  if (!all(is_numeric_token(first_tokens))) {
    stop_error(
      "Numeric matrix appears to contain non-numeric values in the first row. ",
      "Module 2 expects no row/column names: ", path
    )
  }
  
  field_counts <- count.fields(path, sep = "\t", quote = "", comment.char = "")
  if (length(field_counts) == 0) stop_error("Numeric matrix has no rows: ", path)
  if (any(is.na(field_counts))) stop_error("Failed to count fields in numeric matrix: ", path)
  if (length(unique(field_counts)) != 1) {
    stop_error(
      "Numeric matrix has inconsistent numbers of columns across rows: ", path,
      "; observed counts: ", paste(head(unique(field_counts), 10), collapse = ", ")
    )
  }
  
  n_rows <- length(field_counts)
  n_cols <- unique(field_counts)[[1]]
  if (n_rows != n_cols) {
    stop_error("Numeric matrix must be square. Observed ", n_rows, " rows x ", n_cols, " columns: ", path)
  }
  
  list(n_rows = n_rows, n_cols = n_cols)
}

##### 4. Ripser++ execution ####################################################

build_ripser_args <- function(format, max_dim, threshold, ratio, sparse, extra_args, input_path) {
  args <- c(
    "--format", as.character(format),
    "--dim", as.character(max_dim),
    "--threshold", as.character(threshold),
    "--ratio", as.character(ratio)
  )
  if (isTRUE(sparse)) args <- c(args, "--sparse")
  if (!is.null(extra_args) && nzchar(extra_args)) {
    args <- c(args, strsplit(extra_args, "[[:space:]]+")[[1]])
  }
  c(args, input_path)
}

run_ripser_one <- function(ripser_bin, input_path, output_path, ripser_args, gpu_id = NULL) {
  env_old <- Sys.getenv("CUDA_VISIBLE_DEVICES", unset = NA_character_)
  if (!is.null(gpu_id) && nzchar(gpu_id)) {
    Sys.setenv(CUDA_VISIBLE_DEVICES = gpu_id)
  }
  on.exit({
    if (is.na(env_old)) {
      Sys.unsetenv("CUDA_VISIBLE_DEVICES")
    } else {
      Sys.setenv(CUDA_VISIBLE_DEVICES = env_old)
    }
  }, add = TRUE)
  
  stdout_file <- output_path
  stderr_file <- tempfile(pattern = "ripser_stderr_")
  exit_code <- suppressWarnings(system2(
    command = ripser_bin,
    args = ripser_args,
    stdout = stdout_file,
    stderr = stderr_file
  ))
  if (is.null(exit_code)) exit_code <- 0
  
  stderr_text <- if (file.exists(stderr_file)) paste(readLines(stderr_file, warn = FALSE), collapse = "\n") else ""
  if (nzchar(stderr_text)) {
    cat("\n========== STDERR ==========" , "\n", file = output_path, append = TRUE, sep = "")
    cat(stderr_text, "\n", file = output_path, append = TRUE, sep = "")
    cat("========== END STDERR ==========" , "\n", file = output_path, append = TRUE, sep = "")
  }
  unlink(stderr_file)
  
  as.integer(exit_code)
}

##### 5. Ripser++ parser #######################################################

parse_ripser_output <- function(path, matrix_id) {
  check_file_exists(path, "Ripser++ output")
  lines <- readLines(path, warn = FALSE)
  if (length(lines) == 0) {
    return(data.frame(
      matrix_id = character(), interval_id = integer(), homology_feature_id = character(),
      dimension = integer(), birth = numeric(), death = numeric(), lifespan = numeric(),
      is_infinite = logical(), raw_interval = character(), ripser_output = character(),
      stringsAsFactors = FALSE
    ))
  }
  
  lines_trim <- trimws(lines)
  dim_match <- regexec("^persistence intervals in dim[[:space:]]+([0-9]+)[[:space:]]*:[[:space:]]*$", lines_trim)
  dim_capture <- regmatches(lines_trim, dim_match)
  dim_vec <- rep(NA_integer_, length(lines_trim))
  for (i in seq_along(dim_capture)) {
    if (length(dim_capture[[i]]) == 2) dim_vec[[i]] <- as.integer(dim_capture[[i]][[2]])
  }
  
  current_dim <- NA_integer_
  active_dim <- rep(NA_integer_, length(lines_trim))
  for (i in seq_along(lines_trim)) {
    if (!is.na(dim_vec[[i]])) current_dim <- dim_vec[[i]]
    active_dim[[i]] <- current_dim
  }
  
  interval_match <- regexec("^\\[[[:space:]]*([^,]+)[[:space:]]*,[[:space:]]*([^\\)]*)\\)$", lines_trim)
  interval_capture <- regmatches(lines_trim, interval_match)
  is_interval <- vapply(interval_capture, length, integer(1)) == 3 & !is.na(active_dim)
  
  if (!any(is_interval)) {
    return(data.frame(
      matrix_id = character(), interval_id = integer(), homology_feature_id = character(),
      dimension = integer(), birth = numeric(), death = numeric(), lifespan = numeric(),
      is_infinite = logical(), raw_interval = character(), ripser_output = character(),
      stringsAsFactors = FALSE
    ))
  }
  
  interval_idx <- which(is_interval)
  births <- numeric(length(interval_idx))
  deaths <- numeric(length(interval_idx))
  raw_deaths <- character(length(interval_idx))
  
  for (k in seq_along(interval_idx)) {
    cap <- interval_capture[[interval_idx[[k]]]]
    births[[k]] <- suppressWarnings(as.numeric(trimws(cap[[2]])))
    raw_deaths[[k]] <- trimws(cap[[3]])
    deaths[[k]] <- if (raw_deaths[[k]] == "") Inf else suppressWarnings(as.numeric(raw_deaths[[k]]))
  }
  
  dims <- active_dim[interval_idx]
  interval_df <- data.frame(
    matrix_id = matrix_id,
    interval_id = seq_along(interval_idx),
    dimension = as.integer(dims),
    birth = births,
    death = deaths,
    raw_interval = lines_trim[interval_idx],
    ripser_output = normalize_path_if_exists(path),
    stringsAsFactors = FALSE
  )
  
  interval_df$is_infinite <- is.infinite(interval_df$death)
  interval_df$lifespan <- interval_df$death - interval_df$birth
  interval_df$lifespan[interval_df$is_infinite] <- Inf
  
  interval_df <- interval_df[order(interval_df$dimension, interval_df$birth, interval_df$death), , drop = FALSE]
  interval_df$feature_index_within_dimension <- ave(
    interval_df$interval_id,
    interval_df$dimension,
    FUN = seq_along
  )
  interval_df$homology_feature_id <- paste0(
    "H", interval_df$dimension, "_",
    interval_df$feature_index_within_dimension
  )
  
  interval_df[, c(
    "matrix_id", "interval_id", "homology_feature_id", "dimension",
    "birth", "death", "lifespan", "is_infinite", "raw_interval", "ripser_output"
  )]
}

summarize_barcode <- function(barcode_df) {
  if (nrow(barcode_df) == 0) {
    return(data.frame(
      matrix_id = character(), dimension = integer(), n_features = integer(),
      n_finite = integer(), n_infinite = integer(), min_birth = numeric(),
      max_birth = numeric(), min_death = numeric(), max_death = numeric(),
      total_finite_lifespan = numeric(), mean_finite_lifespan = numeric(),
      stringsAsFactors = FALSE
    ))
  }
  
  split_df <- split(barcode_df, paste(barcode_df$matrix_id, barcode_df$dimension, sep = "\t"))
  out <- lapply(split_df, function(df) {
    finite_df <- df[is.finite(df$death), , drop = FALSE]
    data.frame(
      matrix_id = df$matrix_id[[1]],
      dimension = df$dimension[[1]],
      n_features = nrow(df),
      n_finite = nrow(finite_df),
      n_infinite = sum(df$is_infinite),
      min_birth = ifelse(nrow(df) > 0, min(df$birth, na.rm = TRUE), NA_real_),
      max_birth = ifelse(nrow(df) > 0, max(df$birth, na.rm = TRUE), NA_real_),
      min_death = ifelse(nrow(finite_df) > 0, min(finite_df$death, na.rm = TRUE), NA_real_),
      max_death = ifelse(nrow(finite_df) > 0, max(finite_df$death, na.rm = TRUE), NA_real_),
      total_finite_lifespan = ifelse(nrow(finite_df) > 0, sum(finite_df$lifespan, na.rm = TRUE), 0),
      mean_finite_lifespan = ifelse(nrow(finite_df) > 0, mean(finite_df$lifespan, na.rm = TRUE), NA_real_),
      stringsAsFactors = FALSE
    )
  })
  do.call(rbind, out)
}

##### 6. Topological-index plotting ###########################################

# Each persistence interval is drawn as a horizontal segment from birth to
# death. Within each group, H0 intervals are ordered by displayed death, whereas
# intervals in H1 and all higher dimensions are ordered by birth. The other
# endpoint and interval_id are used as deterministic tie-breakers. This rank is
# the topological index. Infinite intervals are displayed up to the largest
# finite filtration value present in the plotted dimension (or the Ripser++
# threshold if no finite endpoint exists).
prepare_topological_index_data <- function(barcode_df, dimension, group_order,
                                           ripser_threshold) {
  plot_df <- barcode_df[
    barcode_df$dimension == dimension &
      is.finite(barcode_df$birth) &
      !is.na(barcode_df$matrix_id),
    ,
    drop = FALSE
  ]
  
  if (nrow(plot_df) == 0) return(plot_df)
  
  finite_endpoints <- c(
    plot_df$birth[is.finite(plot_df$birth)],
    plot_df$death[is.finite(plot_df$death)]
  )
  finite_endpoints <- finite_endpoints[is.finite(finite_endpoints)]
  
  if (length(finite_endpoints) > 0) {
    display_cap <- max(finite_endpoints, na.rm = TRUE)
  } else {
    display_cap <- ripser_threshold
  }
  if (!is.finite(display_cap) || display_cap <= 0) {
    display_cap <- if (is.finite(ripser_threshold) && ripser_threshold > 0) {
      ripser_threshold
    } else {
      1
    }
  }
  
  plot_df$display_death <- plot_df$death
  plot_df$display_death[!is.finite(plot_df$display_death)] <- display_cap
  plot_df$display_death <- pmax(plot_df$display_death, plot_df$birth)
  plot_df$matrix_id <- factor(plot_df$matrix_id, levels = group_order)
  
  indexed_groups <- lapply(group_order, function(group_id) {
    df <- plot_df[as.character(plot_df$matrix_id) == group_id, , drop = FALSE]
    if (nrow(df) == 0) return(NULL)
    if (dimension == 0L) {
      # H0 components are indexed by the threshold at which they merge/die.
      df <- df[
        order(df$display_death, df$birth, df$interval_id),
        ,
        drop = FALSE
      ]
    } else {
      # Cycles and higher-dimensional features are indexed by their appearance.
      df <- df[
        order(df$birth, df$display_death, df$interval_id),
        ,
        drop = FALSE
      ]
    }
    df$topological_index <- seq_len(nrow(df))
    df
  })
  indexed_groups <- indexed_groups[!vapply(indexed_groups, is.null, logical(1))]
  if (length(indexed_groups) == 0) return(plot_df[0, , drop = FALSE])
  
  out <- do.call(rbind, indexed_groups)
  rownames(out) <- NULL
  attr(out, "display_cap") <- display_cap
  out
}

draw_topological_index_plot <- function(plot_df, dimension, group_order,
                                        group_labels, group_colors) {
  if (nrow(plot_df) == 0) {
    plot.new()
    title(main = paste0("H", dimension, " persistent homology"))
    text(0.5, 0.5, paste0("No H", dimension, " intervals were detected"))
    return(invisible(NULL))
  }
  
  display_cap <- attr(plot_df, "display_cap")
  x_min <- min(0, plot_df$birth, na.rm = TRUE)
  x_max <- max(display_cap, plot_df$display_death, na.rm = TRUE)
  if (!is.finite(x_max) || x_max <= x_min) x_max <- x_min + 1
  y_max <- max(plot_df$topological_index, na.rm = TRUE)
  if (!is.finite(y_max) || y_max < 1) y_max <- 1
  
  old_par <- par(no.readonly = TRUE)
  on.exit(par(old_par), add = TRUE)
  par(mar = c(5.0, 5.2, 3.2, 1.0), las = 1)
  
  plot(
    NA_real_, NA_real_,
    xlim = c(x_min, x_max),
    ylim = c(0, y_max),
    xlab = "threshold",
    ylab = "topological index",
    main = paste0("H", dimension, " persistent homology"),
    bty = "l",
    xaxs = "i",
    yaxs = "i"
  )
  grid(col = "grey90", lty = 1)
  
  alpha_colors <- grDevices::adjustcolor(group_colors, alpha.f = 0.5)
  group_counts <- integer(length(group_order))
  
  for (i in seq_along(group_order)) {
    group_df <- plot_df[
      as.character(plot_df$matrix_id) == group_order[[i]],
      ,
      drop = FALSE
    ]
    group_counts[[i]] <- nrow(group_df)
    if (nrow(group_df) == 0) next
    segments(
      x0 = group_df$birth,
      y0 = group_df$topological_index,
      x1 = group_df$display_death,
      y1 = group_df$topological_index,
      col = alpha_colors[[i]],
      lwd = 1.2
    )
  }
  
  legend(
    "bottomright",
    legend = paste0(group_labels, " (n=", format(group_counts, big.mark = ","), ")"),
    col = alpha_colors,
    lwd = 4,
    bty = "n",
    cex = 0.9
  )
  invisible(NULL)
}

write_topological_index_plots <- function(barcode_df, plot_dir, prefix,
                                          max_dim, ripser_threshold,
                                          plot_format, group_labels,
                                          group_colors, plot_width,
                                          plot_height, plot_dpi) {
  group_order <- unique(as.character(barcode_df$matrix_id))
  group_order <- group_order[!is.na(group_order) & nzchar(group_order)]
  if (length(group_order) == 0) {
    message_warn("No barcode groups are available for plotting.")
    return(data.frame(
      dimension = integer(), figure_format = character(), figure_path = character(),
      stringsAsFactors = FALSE
    ))
  }
  
  if (is.null(group_labels)) group_labels <- group_order
  if (length(group_labels) != length(group_order)) {
    stop_error(
      "--plot-labels must contain exactly ", length(group_order),
      " comma-separated label(s), matching input-list order."
    )
  }
  if (length(group_colors) < length(group_order)) {
    group_colors <- grDevices::hcl.colors(length(group_order), palette = "Dark 3")
  } else {
    group_colors <- group_colors[seq_along(group_order)]
  }
  
  dimensions_to_plot <- intersect(c(0L, 1L), seq.int(0L, max_dim))
  plot_records <- list()
  record_index <- 0L
  
  for (dimension in dimensions_to_plot) {
    plot_df <- prepare_topological_index_data(
      barcode_df = barcode_df,
      dimension = dimension,
      group_order = group_order,
      ripser_threshold = ripser_threshold
    )
    
    formats <- if (plot_format == "both") c("png", "pdf") else plot_format
    for (figure_format in formats) {
      figure_path <- file.path(
        plot_dir,
        paste0(prefix, "_module2_H", dimension, "_topological_index.", figure_format)
      )
      
      if (figure_format == "png") {
        grDevices::png(
          filename = figure_path,
          width = plot_width,
          height = plot_height,
          units = "in",
          res = plot_dpi
        )
      } else {
        grDevices::pdf(
          file = figure_path,
          width = plot_width,
          height = plot_height,
          useDingbats = FALSE
        )
      }
      
      tryCatch(
        draw_topological_index_plot(
          plot_df = plot_df,
          dimension = dimension,
          group_order = group_order,
          group_labels = group_labels,
          group_colors = group_colors
        ),
        finally = grDevices::dev.off()
      )
      
      record_index <- record_index + 1L
      plot_records[[record_index]] <- data.frame(
        dimension = dimension,
        figure_format = figure_format,
        figure_path = normalize_path_if_exists(figure_path),
        stringsAsFactors = FALSE
      )
      message_info("H", dimension, " plot: ", figure_path)
    }
  }
  
  if (length(plot_records) == 0) {
    return(data.frame(
      dimension = integer(), figure_format = character(), figure_path = character(),
      stringsAsFactors = FALSE
    ))
  }
  do.call(rbind, plot_records)
}

##### 7. Main #################################################################

main <- function() {
  argv <- commandArgs(trailingOnly = TRUE)
  if (length(argv) == 0 || any(argv %in% c("--help", "-h"))) {
    print_usage()
    quit(save = "no", status = 0)
  }
  
  args <- parse_args(argv)
  
  input_list <- get_arg(args, "input-list", required = TRUE)
  ripser_bin <- get_arg(args, "ripser-bin", required = TRUE)
  outdir <- get_arg(args, "outdir", required = TRUE)
  prefix <- get_arg(args, "prefix", default = "analysis")
  
  ripser_format <- get_arg(args, "format", default = "distance")
  max_dim <- as.integer(get_arg(args, "max-dim", default = "1"))
  threshold <- as.numeric(get_arg(args, "threshold", default = "100"))
  ratio <- as.numeric(get_arg(args, "ratio", default = "1"))
  sparse <- as_logical_arg(get_arg(args, "sparse", default = "true"))
  gpu_id <- get_arg(args, "gpu-id", default = NULL)
  extra_args <- get_arg(args, "extra-args", default = "")
  validate_matrix <- as_logical_arg(get_arg(args, "validate-matrix", default = "true"))
  run_ripser <- as_logical_arg(get_arg(args, "run-ripser", default = "true"))
  continue_on_error <- as_logical_arg(get_arg(args, "continue-on-error", default = "true"))
  make_plots <- as_logical_arg(get_arg(args, "make-plots", default = "true"))
  plot_format <- tolower(get_arg(args, "plot-format", default = "both"))
  plot_labels_arg <- get_arg(args, "plot-labels", default = NULL)
  plot_colors_arg <- get_arg(args, "plot-colors", default = "#56B4E9,#E64B4B")
  plot_width <- as.numeric(get_arg(args, "plot-width", default = "6"))
  plot_height <- as.numeric(get_arg(args, "plot-height", default = "6"))
  plot_dpi <- as.integer(get_arg(args, "plot-dpi", default = "300"))
  
  plot_labels <- if (is.null(plot_labels_arg)) {
    NULL
  } else {
    trimws(strsplit(plot_labels_arg, ",", fixed = TRUE)[[1]])
  }
  plot_colors <- trimws(strsplit(plot_colors_arg, ",", fixed = TRUE)[[1]])
  
  if (is.na(max_dim) || max_dim < 0) stop_error("--max-dim must be a non-negative integer.")
  if (is.na(threshold) || threshold < 0) stop_error("--threshold must be a non-negative number.")
  if (is.na(ratio) || ratio <= 0) stop_error("--ratio must be a positive number.")
  if (!plot_format %in% c("png", "pdf", "both")) {
    stop_error("--plot-format must be one of: png, pdf, both.")
  }
  if (!is.finite(plot_width) || plot_width <= 0) stop_error("--plot-width must be positive.")
  if (!is.finite(plot_height) || plot_height <= 0) stop_error("--plot-height must be positive.")
  if (is.na(plot_dpi) || plot_dpi <= 0) stop_error("--plot-dpi must be a positive integer.")
  if (length(plot_colors) == 0 || any(!nzchar(plot_colors))) {
    stop_error("--plot-colors must contain valid comma-separated R colors.")
  }
  invalid_colors <- vapply(plot_colors, function(x) {
    inherits(try(grDevices::col2rgb(x), silent = TRUE), "try-error")
  }, logical(1))
  if (any(invalid_colors)) {
    stop_error("Invalid --plot-colors value(s): ", paste(plot_colors[invalid_colors], collapse = ", "))
  }
  
  ensure_dir(outdir)
  raw_dir <- file.path(outdir, "raw_ripser_output")
  barcode_dir <- file.path(outdir, "barcode_tables")
  log_dir <- file.path(outdir, "logs")
  plot_dir <- file.path(outdir, "plots")
  ensure_dir(raw_dir)
  ensure_dir(barcode_dir)
  ensure_dir(log_dir)
  if (isTRUE(make_plots)) ensure_dir(plot_dir)
  
  check_file_exists(input_list, "Input list")
  if (isTRUE(run_ripser)) {
    check_file_exists(ripser_bin, "Ripser++ executable")
    if (file.access(ripser_bin, mode = 1) != 0) {
      stop_error(
        "Ripser++ is not executable. Please run chmod +x or provide a valid --ripser-bin: ",
        ripser_bin
      )
    }
  }
  
  manifest <- read_input_list(input_list)
  message_info("Loaded ", nrow(manifest), " matrix path(s) from input list.")
  
  run_records <- vector("list", nrow(manifest))
  barcode_records <- list()
  
  for (i in seq_len(nrow(manifest))) {
    matrix_id <- manifest$matrix_id[[i]]
    matrix_path <- manifest$matrix_path[[i]]
    raw_output <- file.path(raw_dir, paste0(prefix, "_", matrix_id, "_ripserpp.txt"))
    barcode_output <- file.path(barcode_dir, paste0(prefix, "_", matrix_id, "_barcode.tsv"))
    
    message_info("Processing [", i, "/", nrow(manifest), "]: ", matrix_id)
    
    result <- tryCatch({
      check_file_exists(matrix_path, "Numeric matrix")
      
      n_rows <- NA_integer_
      n_cols <- NA_integer_
      validation_status <- "not_requested"
      
      if (isTRUE(validate_matrix)) {
        validation <- validate_numeric_matrix_file(matrix_path)
        n_rows <- validation$n_rows
        n_cols <- validation$n_cols
        validation_status <- "passed"
      }
      
      ripser_args <- build_ripser_args(
        format = ripser_format,
        max_dim = max_dim,
        threshold = threshold,
        ratio = ratio,
        sparse = sparse,
        extra_args = extra_args,
        input_path = matrix_path
      )
      
      command_string <- paste(
        shQuote(ripser_bin),
        paste(shQuote(ripser_args), collapse = " ")
      )
      
      if (isTRUE(run_ripser)) {
        message_info("Running Ripser++ for ", matrix_id)
        exit_code <- run_ripser_one(
          ripser_bin = ripser_bin,
          input_path = matrix_path,
          output_path = raw_output,
          ripser_args = ripser_args,
          gpu_id = gpu_id
        )
        
        if (!identical(exit_code, 0L)) {
          stop_error(
            "Ripser++ failed for ", matrix_id,
            " with exit code ", exit_code
          )
        }
      } else {
        command_string <- paste("[parse-only]", command_string)
        if (!file.exists(raw_output)) {
          stop_error(
            "--run-ripser false requires existing raw output: ",
            raw_output
          )
        }
        exit_code <- 0L
      }
      
      barcode_df <- parse_ripser_output(raw_output, matrix_id = matrix_id)
      write_tsv(barcode_df, barcode_output)
      
      run_record <- data.frame(
        matrix_id = matrix_id,
        matrix_path = normalize_path_if_exists(matrix_path),
        n_rows = n_rows,
        n_cols = n_cols,
        validation_status = validation_status,
        raw_ripser_output = normalize_path_if_exists(raw_output),
        barcode_table = normalize_path_if_exists(barcode_output),
        ripser_command = command_string,
        exit_code = exit_code,
        status = "ok",
        error_message = "",
        stringsAsFactors = FALSE
      )
      
      list(
        run_record = run_record,
        barcode = barcode_df
      )
    }, error = function(e) {
      error_message <- conditionMessage(e)
      message_warn(error_message)
      
      if (!file.exists(raw_output)) {
        cat("[ERROR] ", error_message, "\n", file = raw_output, sep = "")
      } else {
        cat(
          "\n========== MODULE2 ERROR ==========\n",
          file = raw_output,
          append = TRUE
        )
        cat(error_message, "\n", file = raw_output, append = TRUE)
        cat(
          "========== END MODULE2 ERROR ==========\n",
          file = raw_output,
          append = TRUE
        )
      }
      
      failed_record <- data.frame(
        matrix_id = matrix_id,
        matrix_path = normalize_path_if_exists(matrix_path),
        n_rows = NA_integer_,
        n_cols = NA_integer_,
        validation_status = if (isTRUE(validate_matrix)) "failed" else "not_requested",
        raw_ripser_output = normalize_path_if_exists(raw_output),
        barcode_table = normalize_path_if_exists(barcode_output),
        ripser_command = NA_character_,
        exit_code = NA_integer_,
        status = "failed",
        error_message = error_message,
        stringsAsFactors = FALSE
      )
      
      if (!isTRUE(continue_on_error)) {
        stop(e)
      }
      
      list(
        run_record = failed_record,
        barcode = NULL
      )
    })
    
    run_records[[i]] <- result$run_record
    
    if (!is.null(result$barcode)) {
      barcode_records[[matrix_id]] <- result$barcode
    }
  }
  
  run_manifest <- do.call(rbind, run_records)
  if (is.null(run_manifest) || nrow(run_manifest) == 0) {
    stop_error("Module 2 produced no run records.")
  }
  
  run_manifest_path <- file.path(
    outdir,
    paste0(prefix, "_module2_run_manifest.tsv")
  )
  write_tsv(run_manifest, run_manifest_path)
  
  if (length(barcode_records) > 0) {
    combined_barcode <- do.call(rbind, barcode_records)
    rownames(combined_barcode) <- NULL
  } else {
    combined_barcode <- data.frame(
      matrix_id = character(),
      interval_id = integer(),
      homology_feature_id = character(),
      dimension = integer(),
      birth = numeric(),
      death = numeric(),
      lifespan = numeric(),
      is_infinite = logical(),
      raw_interval = character(),
      ripser_output = character(),
      stringsAsFactors = FALSE
    )
  }
  
  combined_barcode_path <- file.path(
    outdir,
    paste0(prefix, "_module2_barcode_all.tsv")
  )
  write_tsv(combined_barcode, combined_barcode_path)
  
  plot_manifest_path <- file.path(
    outdir,
    paste0(prefix, "_module2_plot_manifest.tsv")
  )
  if (isTRUE(make_plots)) {
    plot_manifest <- write_topological_index_plots(
      barcode_df = combined_barcode,
      plot_dir = plot_dir,
      prefix = prefix,
      max_dim = max_dim,
      ripser_threshold = threshold,
      plot_format = plot_format,
      group_labels = plot_labels,
      group_colors = plot_colors,
      plot_width = plot_width,
      plot_height = plot_height,
      plot_dpi = plot_dpi
    )
  } else {
    plot_manifest <- data.frame(
      dimension = integer(), figure_format = character(), figure_path = character(),
      stringsAsFactors = FALSE
    )
  }
  write_tsv(plot_manifest, plot_manifest_path)
  
  summary_df <- summarize_barcode(combined_barcode)
  summary_path <- file.path(
    outdir,
    paste0(prefix, "_module2_homology_summary.tsv")
  )
  write_tsv(summary_df, summary_path)
  
  module3_manifest <- run_manifest[
    run_manifest$status == "ok",
    c("matrix_id", "matrix_path", "raw_ripser_output", "barcode_table"),
    drop = FALSE
  ]
  
  module3_manifest_path <- file.path(
    outdir,
    paste0(prefix, "_module3_input_manifest.tsv")
  )
  write_tsv(module3_manifest, module3_manifest_path)
  
  message_info("Module 2 completed.")
  message_info("Run manifest: ", run_manifest_path)
  message_info("Combined barcode table: ", combined_barcode_path)
  message_info("Homology summary: ", summary_path)
  message_info("Plot manifest: ", plot_manifest_path)
  message_info("Module 3 input manifest: ", module3_manifest_path)
  message_info(
    "Successful run(s): ", sum(run_manifest$status == "ok"),
    "; failed run(s): ", sum(run_manifest$status != "ok")
  )
  
  failed_n <- sum(run_manifest$status != "ok")
  if (failed_n > 0) {
    message_warn(
      "Module 2 completed with ", failed_n,
      " failed run(s). See run manifest for details."
    )
  }
  
  if (nrow(module3_manifest) == 0) {
    stop_error(
      "Module 2 produced no successful records for Module 3. ",
      "Inspect: ", run_manifest_path
    )
  }
}

main()